---
- name: install and configure Zabbix Database
  hosts: database-servers
  user: root
  sudo: yes
  roles:
  - repo
  - server
  - database

- name: install and configure Zabbix Server
  hosts: zabbix-servers
  user: root
  sudo: yes
  roles:
  - repo
  - server

- name: install and configure Zabbix Web Front End
  hosts: zabbix-agents
  user: root
  sudo: yes
  roles:
  - repo
  - agent
