---
- hosts: zabbix_database_backends
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-database

- hosts: zabbix_server_backends
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-server
    - zabbix-pagerduty
    - firewall

- hosts: zabbix_web_servers
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-web
    - firewall
