---
- hosts: zabbix_database_master
  vars_files:
    - "{{ env }}/group_vars/mysql-master"
  roles:
    - zabbix-agent
    - zabbix-database
    - firewall
    - htop

- hosts: zabbix_database_slave
  vars_files:
    - "{{ env }}/group_vars/mysql-slave"
  roles:
    - zabbix-agent
    - zabbix-database
    - firewall
    - htop

- hosts: zabbix_server_backends
  vars_files:
    - "{{ env }}/group_vars/mysql-master"
    - "{{ env }}/group_vars/mysql-slave"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - zabbix-agent
    - zabbix-server
    - zabbix-pagerduty
    - firewall
    - htop

- hosts: zabbix_web_servers
  vars_files:
    - "{{ env }}/group_vars/mysql-master"
    - "{{ env }}/group_vars/mysql-slave"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - zabbix-agent
    - zabbix-web
    - firewall
