---
- hosts: zabbix-database-backends
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-database

- hosts: zabbix-server-backends
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-server

- hosts: zabbix-web-servers
  vars_files:
    - "{{ env }}/group_vars/zabbix-database-server"
    - "{{ env }}/group_vars/zabbix-server"
  roles:
    - common
    - zabbix-agent
    - zabbix-web
